[package]
name = "bitwarp-utilities"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "MIT"

[lib]
doctest = false

[dependencies]
dns-lookup.workspace = true

[lints]
workspace = true
